@startuml

entity "User" as e1 {
  +id: string 
  --
  name: string
  password: string 
  userName: string 
  email: string 
  creationDate: date
}

entity "UserProject" as e2 {
  +id(userID, adminID): string 
  --
  roles: string 
  joinDate: date 
}

entity "Project" as e3 {
  +id: string 
  --
  description: string
  projectType: string
  numberOfMember: int
  creatorID: string
  startDate: date
  endDate: date 
}

entity "Tasks" as e4 {
  +id: string 
  --
  mainTaskId: string
  description: string
  createBy: string
  assignToUserId: string 
  creationDate: date
  creatorID: string
  ownerID: string 
  startDate: date    
  endDate: date  
}

e1 ||--o{ e2 : "member of "
e1 ||--o{ e3 : "creator of"
e3 ||--o{ e4 : "have" 

e1 ||--o{ e4 : "own"  
e1 ||--o{ e4 : "created"  
e3 ||--o{ e2 : "include"
e4 ||-o{ e4 : "subTasks"
e4 ||-o{ e1 : "assign"


@enduml